name: checksums

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-checksums:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Create checksums
        run: |
          git config user.name 'Botspot'
          git config user.email 'botspot@users.noreply.github.com'
          sha256sum ./* > sha256sums.txt
          git add sha256sums.txt
          git commit -m "checksum update"
          git push origin main
